### ISSUE TITLE
Publish v3.5.0

### ISSUE THREAD

**Issue by alexdrean** [hapijs/shot#107]
Hi,

Version 3.5.0 has not been published to npm.
[See here](https://www.npmjs.com/package/shot) -> "versions"
This causes my `npm install` to fail:
`npm ERR! 404 Not Found: shot@https://registry.npmjs.org/shot/-/shot-3.5.0.tgz`

Thank you.

**Comment by hueniverse** [comment]
There is not going to be an open source version of 3.x. It is only available under a commercial license:

https://www.npmjs.com/package/@commercial/shot

Version 4 is available under an open source license while it is under active support per hapi support policies.
