### ISSUE TITLE
Node V12 deprecation warning [DEP0066] OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by yonjah** [hapijs/shot#108]
When using latest hapi (v18.3.1) and shot (v4.1.0) with Node V12 a [deprecation warning](https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames) is thrown from [response.js:18](https://github.com/hapijs/shot/blob/master/lib/response.js#L18)  -

```shell
(node:32073) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at new module.exports.internals.Response (node_modules/@hapi/shot/lib/response.js:18:23)
    at node_modules/@hapi/shot/lib/index.js:58:21
```

**Comment by hueniverse** [comment]
Will take a bit to get to all these in the org.

**Comment by SimonSchick** [comment]
@hueniverse would version detection ala `process.version.startsWith('v8.')` be an acceptable solution here?
