### ISSUE TITLE
Simulate 'disconnect' event?

### ISSUE THREAD

**Issue by achingbrain** [hapijs/shot#121]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 12
* *module version*: 5.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*:

#### How can we help?

Is it possible to simulate a `disconnect` event on the injected request?

I can see `close`, `finish`, etc in the docs but not `disconnect`.  Adding it to the `simulate` hash causes a validation error to be thrown.

**Comment by hueniverse** [comment]
That's not supported.

**Comment by achingbrain** [comment]
That's certainly what I observed. Would you accept a PR that adds support for it?

**Comment by hueniverse** [comment]
Sorry but no. hapi core dones't listen to a `disconnect` event on the request/response stream so there is no need for it.

**Comment by achingbrain** [comment]
I'm using hapi for RPC-over-HTTP and have low-level components that can create long-lived resources in response to user requests - I'm trying to signal to those components that the result of the operation is no longer required so they can tear down anything they've created within the context of the request.

At the moment I'm listening for a `disconnect` on the incoming HTTP request (which as I understand it means the client closed the connection) and using that to trigger the `abort` event on an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) passed down the stack and am trying to write tests for it.

If there's no chance of this event being added to shot, do you know if there is a better, testable way to do this with hapi?

**Comment by hueniverse** [comment]
@kanongil ideas?
