### ISSUE TITLE
Test suite failing on Node.js v14.6.0

### ISSUE THREAD

**Issue by MylesBorins** [hapijs/shot#128]
This is due to new global variables that are unknown to lab

I've opened a PR to fix this -> https://github.com/hapijs/lab/pull/981

Until this is fixed we are skipping shot on v14.x in CITGM https://github.com/nodejs/citgm/pull/813

Once the upstream lab fix has landed and shot has been fixed we can revert that change on CITGM

**Comment by cjihrig** [comment]
`@hapi/lab@22.0.5` was published with https://github.com/hapijs/lab/commit/0a5adf0d56d7aa118410a28afc51d922e172196a. The `shot` CI is [now passing](https://travis-ci.org/github/hapijs/shot/jobs/710214180) on Node v14.6.0.

**Comment by MylesBorins** [comment]
shot has been re-enabled on citgm

**Comment by MylesBorins** [comment]
Hey @cjihrig shot is still failing in CI because the lab update hasn't landed in a release (at least that is my assumption). Are you planning a release soon or should we remove shot from CITGM for the time being?

**Comment by cjihrig** [comment]
Any chance you're running into caching issues? The lab change was published as 22.0.5, and shot relies on 22.x.x. Can you verify that CITGM is testing against lab 22.0.5?

**Comment by MylesBorins** [comment]
Unsure if it is a caching thing... I just reproduced locally with ` npx citgm -v verbose shot`

I was also able to reproduce in a clone of the shot repository with a fresh npm install

**Comment by cjihrig** [comment]
`npx citgm -v verbose shot` doesn't work for me locally. I get this warning:

```
primordials is not defined
Warn   |update-available    |v7.1.1 (current: v0.1.0)
       |                    |npm install -g citgm   
```

> I was also able to reproduce in a clone of the shot repository with a fresh npm install

I did a fresh clone with a fresh npm install, and it worked fine for me. Can you run `npm ls @hapi/lab`:

```
$ npm ls @hapi/lab
@hapi/shot@5.0.0 /private/tmp/shot
└── @hapi/lab@22.0.5 

```

**Comment by MylesBorins** [comment]
I flushed my cache and removed a local package-lock.json and managed to get
it working... so indeed it sounds like a caching issue in CITGM.

**Comment by cjihrig** [comment]
Cool. FWIW, we are due to publish a new major version of `lab` and a new patch version of `shot`. Those should be out tonight or tomorrow.
