### ISSUE TITLE
Failure on 0.10 with Express 3.20

### ISSUE THREAD

**Issue by aredridel** [hapijs/shot#29]
With this test:

```
var test = require('tape');

var shot = require('shot');

var app = require('express')();

test('works?', function (t) {
    shot.inject(app, {url: '/'}, function (res) {
        t.end();
    });
});
```

I get 

```
TAP version 13
# works?

http.js:348
  if (this.socket.readable)
                 ^
TypeError: Cannot read property 'readable' of undefined
    at IncomingMessage._read (http.js:348:18)
    at IncomingMessage.Readable.read (_stream_readable.js:341:10)
    at IncomingMessage.read (http.js:340:15)
    at IncomingMessage.<anonymous> (_stream_readable.js:764:45)
    at IncomingMessage.emit (events.js:92:17)
    at emitDataEvents (_stream_readable.js:790:10)
    at IncomingMessage.Readable.resume (_stream_readable.js:734:3)
    at send (/Users/ariastewart/Projects/adaro/node_modules/express/node_modules/connect/node_modules/finalhandler/index.js:139:7)
    at Object.<anonymous> (/Users/ariastewart/Projects/adaro/node_modules/express/node_modules/connect/node_modules/finalhandler/index.js:96:5)
    at Object.immediate._onImmediate (timers.js:372:16)
```

**Comment by Marsup** [comment]
I'm not sure `app` can be called with req/res, maybe the router ? I don't think express let's you access that.

**Comment by hueniverse** [comment]
I don't know what `app` is (I don't use express) but it is expecting the dispatch function as shows in the examples. This was only tested against bare node and hapi. I'll leave this open in case you want to dig into how to get the same dispatch function express is creating internally and passing to the node HTTP server. I'll close it in a bit if inactive.

**Comment by dougwilson** [comment]
Hi @hueniverse I think you can probably close this, as I believe this is an issue with Express, rather than with `shot`. @aredridel do you agree with that assessment?

**Comment by aredridel** [comment]
Yeah, I think that's fair. Express is definitely doing unsavory contortions here.

**Comment by garthk** [comment]
Confirmed in Express 4.8.5 and 4.13.3. I'm working on an Express app, now, so here goes:

Installing `stackup` and working backwards from the crash, I'm intrigued at this from [finalhandler 0.4.0](https://github.com/pillarjs/finalhandler/blob/v0.4.0/index.js#L140):

```js
  if (isFinished(req)) {
    write()
    return
  }

  // unpipe everything from the request
  unpipe(req)

  // flush the request
  onFinished(req, write)
  req.resume()
```

`isFinished` and `onFinished` are from [on-finished](https://github.com/jshttp/on-finished/tree/v2.3.0). 

The failing sequence is:

* [`shot/lib/index:292`](https://github.com/hapijs/shot/blob/v1.6.0/lib/index.js#L292):  shot.inject` calls its `dispatchFunc`, aka `app`
* [`express/lib/express.js:38`](https://github.com/strongloop/express/blob/4.13.3/lib/express.js#L38): `app` calls its `app.handle`
* [`express/lib/application.js:173`](https://github.com/strongloop/express/blob/4.13.3/lib/application.js#L173): `app.handle` calls `router.handle` with a [`finalhandler`](https://github.com/pillarjs/finalhandler/tree/v0.4.0) wrapper around the callback but untouched `req` and `res`
* …
* [`express/lib/router/layer.js:95`](https://github.com/strongloop/express/blob/4.13.3/lib/router/layer.js#L95): `handle_request` calls my route handler, which calls `next(err)`
* …
* The router restores some properties lib/router/index.js:618
* [`express/lib/router/index.js:618`](https://github.com/strongloop/express/blob/4.13.3/lib/router/index.js#L618): `restore` passes control to `finalhandler` after restoring `baseUrl`, `next`, and `params` to the `IncomingMessage`
* [`finalhandler/index.js:107`](https://github.com/pillarjs/finalhandler/blob/v0.4.0/index.js#L107): `finalhandler` calls `send` with the same `req` object my request handler saw
* `send` sees `req` isn't finished, so calls `unpipe(req)` and `req.resume`
…
* [`node@0.12.7:lib/_http_incoming.js104`](https://github.com/nodejs/node-v0.x-archive/blob/v0.12.7/lib/_http_incoming.js#L104) tries to check `this.socket.readable` but `this.socket` is `undefined`

`req.socket` is undefined all the way back to [`shot/lib/index:292`](https://github.com/hapijs/shot/blob/v1.6.0/lib/index.js#L292). Hacking in `req.socket = { readable: false }` at that point lets my tests pass.

I think there's a case to be made that this is `shot` disagreeing with the Node standard library, not an Express problem. Could we re-open this issue for long enough to determine whether the `req.socket` assignment above is correct enough to resolve the problem?

**Comment by garthk** [comment]
I don't think this is sufficient. It fixes the problem with `get` with query strings, but I'm still running into trouble posting bodies.
