### ISSUE TITLE
Client IP address

### ISSUE THREAD

**Issue by achingbrain** [hapijs/shot#35]
Is it possible to specify what the IP address of the client making the fake request should appear to be?  

E.g. so we can control what `request.info.remoteAddress` is populated with.

**Comment by mtharrison** [comment]
No, it's not possible to use Shot for that at the moment. The request that is passed to the listener isn't associated with a socket so hapi's (assumed your using hapi because you said `request.info.remoteAddress`) `Request` object has a empty string set as the `remoteAddress`: 

https://github.com/hapijs/hapi/blob/master/lib/request.js#L114

**Comment by hueniverse** [comment]
@achingbrain are you looking to simulate an ip address or try to get the current machine address? If you can provide a use case for the former, I could support that.

**Comment by achingbrain** [comment]
@hueniverse I'm trying to simulate an IP address.

Our use case is that we have a Hapi API that contacts a downstream system.  The downstream system requires that we send the IP address of the client using our API as a header for auditing purposes.  We have sort-of-integration tests that use [nock](https://libraries.io/npm/nock) to stub the downstream system and `server.inject` to simulate incoming requests.

Since we can't affect the value of `request.info.remoteAddress` we can't assert that the correct IP is being sent.

**Comment by hueniverse** [comment]
@achingbrain would you like to try and propose a code change via PR so we can review and consider?

**Comment by mtharrison** [comment]
@achingbrain if you do make a PR, one thing to note is that hapi will bail out of processing a request if it has a `connection` property and the server isn't started:

https://github.com/hapijs/hapi/blob/master/lib/connection.js#L222-L226

So we might require a change over there too? Perhaps we can check for `Shot.isInjection(req)` or for the presence of the `end()` method.

**Comment by mtharrison** [comment]
Once hapi is updated to shot v1.6.0 this feature will be available through `server.inject` with the `remoteAddress` option.

**Comment by achingbrain** [comment]
That's awesome, thank you so much.
