### ISSUE TITLE
shot should allow to make a http request without headers key

### ISSUE THREAD

**Issue by crashuniverse** [hapijs/shot#64]
shot makes some vague assumptions about headers.

At https://github.com/hapijs/shot/blob/master/lib/request.js#L35-L36 it seems shot will always make a request with a blank header object or with ones given in options. `http` doesn't mandate to always have a `request header`. So it makes it a valid use case to have a request without any headers at all, which is why we should, in server side code, check for headers object and then do more with it. Now this instance can't be tested as shot will always have a header object, and add user-agent information in it, with no option to turn all headers off and not have a headers key in request. 

Unless I'm missing something.

**Comment by hueniverse** [comment]
First, what are you using shot for? If its not as part of a hapi project, we don't care (don't mean to be rude, just that this module is exclusively for hapi internal usage like most hapi modules).

Second, HTTP 1.1 does require some headers like host and date.
