### ISSUE TITLE
deprecated encoding 'binary' is used

### ISSUE THREAD

**Issue by iamdoron** [hapijs/shot#7]
in [here](https://github.com/spumko/shot/blob/master/lib/index.js#L190):
```javascript
var output = rawBuffer.toString('binary');
```
from node [buffer documentation](http://nodejs.org/api/buffer.html):

>```'binary'``` - A way of encoding raw binary data into strings by using only the first 8 bits of each character. This encoding method is **deprecated** and *should be avoided* in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.

I was also wondering what happens to the returned payload, since its original encoding may be different.
I would expect something similar to:

```javascript
res.payload = (new Buffer(res.payload.toString(), 'binary')).toString()
```

(for example, the default utf8 encoding will be returned)

**Comment by Marsup** [comment]
@geek I've ~~wasted~~ spent 2 days on this problem, I'd appreciate either a fix or an advice on how to go about it.

Using a template (`reply.view`) having accentuated characters and using `server.inject` from hapi, `prénom` becomes `prÃ©nom` in `response.result`. While it would be OK in `response.payload` because it is supposed to be binary (which I didn't know and it being a string doesn't help coming to this conclusion), I don't see why `response.result` should be that way as well.
Honestly I can't determine if it's hapi or shot's fault, what am I doing wrong ?

**Comment by geek** [comment]
Does the same test pass if you start the server and make a real request?

**Comment by Marsup** [comment]
Yes, the characters are perfectly fine in a real browser.

**Comment by d10** [comment]
:+1: for this. I’ve encountered the same issue, and had to use `res.rawPayload.toString('utf8')` to get my tests to past. This really confused me at the start, and I’m sure others will be confused too.

**Comment by Marsup** [comment]
@chrisdickinson do you have an opinion about that ?

**Comment by hueniverse** [comment]
I took over the module for now. What's the question again?

**Comment by Marsup** [comment]
@hueniverse when you use `server.inject` in hapi, you get a `res.payload` that looks like a string you'd get from the server as a client, when in fact it's the binary form of that string. (eg. if I reply `éèàù` I get `Ã©Ã¨Ã Ã¹` as payload)
I don't want to `new Buffer(res.payload, 'binary').toString('utf8')` everywhere in my tests "just in case".

**Comment by hueniverse** [comment]
We can add another property on `res` that will include the `utf8` encoded version. Would that solve it? I am concerned about a breaking change.

**Comment by d10** [comment]
That seems great! :+1:

**Comment by Marsup** [comment]
This looks like a bug to me, can you explain the documentation `(e.g. when not a stream or a view)` ? If I reply the same string from a handler it works, if from a view it doesn't, why ?

**Comment by hueniverse** [comment]
@Marsup what documentation?

**Comment by Marsup** [comment]
@hueniverse Look for that specific sentence in hapi's docs, it's in server.inject.

**Comment by merrihew** [comment]
We've encountered an issue that have been tracked down to this set of changes to `shot`, specifically `payloadBuffer.toString()` in d9dd737a2cf91d47849f670a67df5cece73067d3 ([commit diff](https://github.com/hapijs/shot/commit/d9dd737a2cf91d47849f670a67df5cece73067d3#diff-6d186b954a58d5bb740f73d84fe39073R232)).

Why was this not considered a breaking change with a major version bump (despite @hueniverse's comment bringing it up)? Bug or not, it's been the way `shot` has returned `res.payload` and people have accommodated for it.  **I think it warrants a revert and a major version bump.**

**Comment by hueniverse** [comment]
@merrihew probably should have been but too late now. In general bug fixes are an exception to the major version rule but this was a case of unexpected impact. The hapi change does flag it with breaking changes label.

**Comment by merrihew** [comment]
@hueniverse Agreed on the fact that it's already out in the wild, so too late to revert. Opens up an interesting semver discussion when a bug has existed for an extended period of time... in our case, we had taken steps to handle the payload "bug", therefore the "fix" actually created a new bug. There's no clear right or wrong way to handle that, and ultimately something we can just work around on our side. Thanks for all of the continued work on `hapi`!
