### ISSUE TITLE
Support multipart requests

### ISSUE THREAD

**Issue by paulfryzel** [hapijs/shot#8]
While shot currently supports POST and an object-based payload, the ability to inject multipart requests doesn't seem to be supported. As a use-case, my personal interest in this functionality is specifically for testing file uploads (as multipart/form-data).

**Comment by jondlm** [comment]
I know this issue is really old, but here's the solution I came up with. It requires the use of the [form-data](https://github.com/form-data/form-data/) library.

```javascript
var FormData = require('form-data');
var fs = require('fs');
// etc..

it('should accept a tarball', function (done) {
  var form = new FormData();
  var bufferChunks = [];

  form.append('file', fs.createReadStream('./test/fixtures/test.tar.gz'));

  form.on('data', function (chunk) {
    bufferChunks.push(new Buffer(chunk));
  });

  form.on('end', function() {
    var buffer = new Buffer.concat(bufferChunks);

    var uploadReq = {
      url: '/api/projects',
      method: 'post',
      payload: buffer,
      headers: form.getHeaders()
    };

    server.inject(uploadReq, function (res) {
      assert.equal(res.statusCode, 200);
      done();
    });
  });

  form.resume(); // this kicks off the readable stream

});
```

**Comment by mtharrison** [comment]
@jondlm thanks for sharing your solution. Looks like a good way to do it to me. Pity you need to read the stream up yourself like that though, it would be a lot nicer if you can use a stream payload:

```javascript
it('should accept a tarball', function (done) {

    var form = new FormData();
    form.append('file', fs.createReadStream('./test/fixtures/test.tar.gz'));

    var uploadReq = {
        url: '/api/projects',
        method: 'post',
        payload: form,
        headers: form.getHeaders()
    };

    server.inject(uploadReq, function (res) {
        assert.equal(res.statusCode, 200);
        done();
    });

});
```

Unfortunately this doesn't work as shot will `JSON.stringify()` the stream.

@hueniverse what's your opinion on Shot allowing stream objects for payloads, in the same way wreck does?

**Comment by hueniverse** [comment]
I am ok with being able to provide a payload stream.

**Comment by jondlm** [comment]
@mtharrison yeah, I tried that at first as well, but ran into problems as you said. That would be sweet, but not a show stopper obviously. It was a good opportunity for me to brush up on the various streams apis.
