### ISSUE TITLE
Express breaks shot such that the callback never gets called

### ISSUE THREAD

**Issue by jfhbrook** [hapijs/shot#82]
Hi!

Unfortunately I don't have a minimum reproducing case, just the app I'm working on. I don't think anything I'm doing in the app right now is particularly controversial, and I'm not sure what things I would remove to rule out. But, at least, there's a working case:

https://github.com/jfhbrook/wzrd.in/tree/782ac0dfa02df7ee245f1f04cb1a3a53100804af

(Requires docker to run.)

This code does a lot of things but the part that I think matters is that I have an [express app](https://github.com/jfhbrook/wzrd.in/blob/782ac0dfa02df7ee245f1f04cb1a3a53100804af/index.js#L18-L31) which [ultimately calls res.end based on the output of a promise](https://github.com/jfhbrook/wzrd.in/blob/782ac0dfa02df7ee245f1f04cb1a3a53100804af/handlers/singular.js#L52);

I've been doing some digging to try to figure out what's going on, and I eventually found out on accident that [I can "fix" this by effectively binding to res](https://github.com/jfhbrook/wzrd.in/blob/782ac0dfa02df7ee245f1f04cb1a3a53100804af/node_modules/shot/lib/index.js#L55-L58) inside of shot itself. Oddly, though I can't find a case of someone doing `res.end.call(someOtherRes)`; anywhere, which would afaict [cause this to not get fired](https://github.com/hapijs/shot/blob/master/lib/response.js#L17-L22).

Any ideas or suggestions?

**Comment by mtharrison** [comment]
I tried to run your example but got the following error:

```
Unable to find image 'browserify-builder:latest' locally
        Pulling repository docker.io/library/browserify-builder
        docker: Error: image library/browserify-builder:latest not found.
```

> but the part that I think matters is that I have an express app which ultimately calls res.end based on the output of a promise;

Can you make a mini example showing if this is the issue? It will be a lot easier for us to debug that way.

**Comment by jfhbrook** [comment]
oh wow, I didn't actually expect you to be willing to do this!

But yes, there's an init step that builds the image locally. You can run it with `./bin/wzrdin bootstrap`. After that, 'npm test' and 'npm start' should work largely as expected.

Sorry for the confusion!

**Comment by jfhbrook** [comment]
I made a branch where I'm starting to try and remove things: https://github.com/jfhbrook/wzrd.in/tree/failing-shot-tests This stubs out the underlying logic/code with a Promise.resolve so I'm certain it's not the underlying "bundler" code.

You can run that test with `node ./test/int-singular.js`.

I'll see if I can make a smaller example, in the meantime.

**Comment by jfhbrook** [comment]
I succeeded in narrowing this down quite a bit! https://github.com/jfhbrook/wzrd.in/blob/failing-shot-tests/test-shot.js

which was generally a good move, because I think this is ultimately related to some [dirty tricks I forgot I was playing with request logging](https://github.com/jfhbrook/wzrd.in/blob/failing-shot-tests/middlewares/request-logger.js#L12-L17). I'm not 100% on what I'm doing here that's causing the seen behavior but it's almost certainly in here.

**Comment by jfhbrook** [comment]
Problem though: I was able to remove the request logging and still reproduce!  Current case:

```js
'use strict';

const http = require('http');

const express = require('express');
const shot = require('shot');

const app = express();

app.get('/foo', function(req, res, next) {
  res.end('foo');
});

console.log('injecting');
shot.inject(app, { url: '/foo' }, (res) => {
  console.log('responded');
  console.log(res);
});
```

"responded" doesn't get called.

**Comment by jfhbrook** [comment]
Express version is 4.14.

**Comment by mtharrison** [comment]
The problem is that Express overwrites the response prototype [here](https://github.com/expressjs/express/blob/master/lib/middleware/init.js#L29) meaning that the overrides done by Shot are lost.

**Comment by devinivy** [comment]
@mtharrison if I were you I wouldn't touch it.  Express has a hard time working with some http/2 libraries for the same reason, and my understanding is that they'll change their approach for express v5.  See https://github.com/expressjs/express/issues/2761.

Looking a little closer, in the checklist for v5 (https://github.com/expressjs/express/pull/2237) I see,
> Support non-core HTTP prototypes (e.g. `http2`, `shot` and others)

**Comment by mtharrison** [comment]
@devinivy thanks for sharing that

**Comment by devinivy** [comment]
No problem!  Also, you can disregard my "if I were you" business.  I think whatever choice you make will be 👍 , but it is at least on express's radar that they need to adjust their approach for better interop.

**Comment by jfhbrook** [comment]
Oh, I see! Great detective work!

I agree that if express is the one misbehaving, that the fix should ultimately live in express. That said, this leaves me (and anyone else using express, which is a lot of people) in a lurch until I can upgrade to whatever hypothetical version of express fixes this.

I can float a patch on my own version of shot if I have to, but maybe the right approach is to add an almost-acceptable express-catering fix and then remove it when what counts as modern express no longer does that?

**Comment by mtharrison** [comment]
I'd like to help but I'd prefer the workaround for it was outside of Shot. Something we could do is perhaps export Shot's response object and let you restore the prototype yourself in a middleware, e.g.:

```js
'use strict';

const http = require('http');

const express = require('express');
const shot = require('shot');

const app = express();

app.use(function (req, res, next) {

    if (req.headers['user-agent'] === 'shot') {
        
        // Restore Shot prototype

        ['write', 'end', 'writeHead', 'destroy'].forEach((method) => {
            res[method] = shot.Response.prototype[method];
        });
    }

    next();
});

app.get('/foo', function(req, res, next) {
  console.log('foo');
  res.end('foo');
});

console.log('injecting');
shot.inject(app, { url: '/foo' }, (res) => {
  console.log('responded');
  console.log(res);
});
```

**Comment by jfhbrook** [comment]
That's awful UX though.

**Comment by jfhbrook** [comment]
Like I said, I'm okay maintaining my own forked codebase for now. But telling users of express they're SOL and need to write 20 lines of response-punching code in order to use your library, well, *my* advice is to eat it.

**Comment by jfhbrook** [comment]
One idea is to add a method that causes shot to run the fixit behavior, something like, `shot.fixDumbStuffInExpress()` that modifies behavior. That way you at least feel like you're making it clear to users that it's express's fault.

**Comment by jfhbrook** [comment]
(I guess I could wrap/fork/publish my own copy of shot with the fix too...)

**Comment by devinivy** [comment]
We don't tell each other to "eat it" in this community.  This is open software that you're welcome to hack on, use, fork, etc., and @mtharrison is being more than helpful with time that he owes to none of us– please be respectful of that.

I doubt that @mtharrison has any particular desire to make it clear whose fault it is that shot and express don't interoperate out of the box.  A fix could live in express, shot, or elsewhere (e.g. an express middleware, or potentially by wrapping shot), and the latter two are going to be a hack either way.  Matt has additionally written essentially all the middleware code necessary to fix your issue for the time being.

To my knowledge you are the first user who has been affected by this, probably because shot is first and foremost used to implement a feature in hapi.  While I don't personally care whether a fix lands in express, shot, or elsewhere, I do care when I see lead maintainers attempted to be bossed around or shamed with the sort of language that you're using here.

**Comment by hueniverse** [comment]
@jfhbrook to be perfectly clear - I don't care at all about people using shot with Express. Shot is designed and maintained exclusively for use with hapi. If it works for you with other frameworks, great. But all I care about is hapi.

**Comment by mtharrison** [comment]
I think it's clear what are feelings are on this.

> I guess I could wrap/fork/publish my own copy of shot with the fix too.

If the other suggestions here don't work for you, go for it.

**Comment by devinivy** [comment]
I would personally vote for a shot wrapper if that's possible! 
```js
const Shot = ForExpress(require('shot'));
```

**Comment by jfhbrook** [comment]
> We don't tell each other to "eat it" in this community.

I think you misunderstood me. I was referring to eating a meal you don't enjoy, not, well, something much more rude. I'm not *that* punk rock.

**Comment by devinivy** [comment]
Haha, I can appreciate that!  Even so, the overall tone made me feel badly because it sounded like Matt had somehow wronged you when he hadn't, and provided help that did little more than punch your response object.  Anyways, my impression is that we're cool 😎.  I also realize you're plenty familiar with maintaining open software that's used by many people with their own various concerns/issues.  If you do wrap shot I'd be interested to see it, since I may have to do something similar to make shot work with HTTP/2.

**Comment by devinivy** [comment]
Just wanted to follow-up to share that I've created a tool that will help you use shot with express.  It involves mounting your express app to a hapi server then calling `server.inject()`.  Or you can peek the approach taken in the code and use it as you wish!

https://github.com/devinivy/hecks
