### ISSUE TITLE
command failed with exit code 1 when running Jest test using server.inject

### ISSUE THREAD

**Issue by nxmohamad** [hapijs/shot#86]
I have a GET /tags route that returns a JSON object, and I'm trying to test it using Jest and server.inject.

This is my first time using server.inject. On this note I am actually not sure whether this falls under shot or just hapi as I don't actually require Shot.

This is my test file:
```
const server = require('../../server');

jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;

it('should return tags', (done) => {
	server.inject('/tags', (res) => {
		expect(res.statusCode).toEqual(200);
		expect(res.result).toBeDefined();
		done();
		done.fail(error)
	});
});
```

When running it, the result is this:
```
/var/www/app/node_modules/jest-matchers/build/index.js:235
        throw error;
        ^

Error: expect(received).toEqual(expected)

Expected value to equal:
  200
Received:
  404
    at server.inject.res (/var/www/app/src/tags/tagsRoutes.test.js:7:26)
    at Shot.inject (/var/www/app/node_modules/hapi/lib/connection.js:329:16)
    at process.nextTick (/var/www/app/node_modules/shot/lib/response.js:27:36)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
error Command failed with exit code 1.
```
The test fail part is understandable (thought I'm not sure yet why it returns 404), but the exit code 1 is unusual. What may be causing it?

**Comment by hueniverse** [comment]
Your test server is returning 404 which means the route is not found. No one can help you with this because the problem is in your code...

**Comment by nxmohamad** [comment]
@hueniverse but is it supposed to make it exit straightaway? instead of leaving my test in watch mode?

**Comment by hueniverse** [comment]
I never used jest.

**Comment by nxmohamad** [comment]
sorry for that. I was trying to do too many things at once. Should have asked this in Jest instead of here. Thank you for your time.
