### ISSUE TITLE
Add cookies to response

### ISSUE THREAD

**Issue by robinvdvleuten** [hapijs/shot#96]
It would be very nice to have an object of all parsed cookies available on the response object. I can make a PR for this if you like.

**Comment by mtharrison** [comment]
I don't this really belongs in shot. Can you explain a bit maybe about your use case?

**Comment by robinvdvleuten** [comment]
Sure! I am testing out the `validateFunc` function of the `hapi-auth-cookie` strategy. I found out that the only way to do that is to do something like this;

```js
test('Cookie strategy errors when token does not exists', async () => {
  expect.assertions(1)

  server.route({
    method: 'GET',
    path: '/inject-session',
    options: {
      handler(request) {
        request.cookieAuth.set({ token: faker.random.alphaNumeric(32) })
        return {}
      },
      auth: false
    }
  })

  server.route({
    method: 'GET',
    path: '/require-session',
    options: {
      handler() {
        return {}
      },
      auth: {
        strategy: 'session',
        scope: ['trusted']
      }
    }
  })

  const res = await server.inject({
    method: 'GET',
    url: '/inject-session'
  })

  const cookie = cookies.parse(res.headers['set-cookie'][0])

  const res2 = await server.inject({
    method: 'GET',
    url: '/require-session',
    headers: { cookie: `sid=${cookie.sid}` }
  })

  expect(res2.statusCode).toBe(302)
})
``` 

It would be nice though if I do not have to parse the cookies myself but get them from shot's response by name.

**Comment by hueniverse** [comment]
Doesn't belong in shot. Easy enough to do write a utility for.

**Comment by mtharrison** [comment]
Going to close this. Shot is pretty low level by intention, it gives you the response headers so you can extract cookies easily from that.
